### ISSUE TITLE
NitrogenOTA doesn't check for already downloaded files

### ISSUE THREAD

**Issue by ghost** [nitrogen-project/android_packages_apps_NitrogenOTA#2]
It seems NitrogenOTA doesn't check if there's an already downloaded ROM zip in the OTA_DOWNLOAD_DIR directory.
This is for example where a user has already downloaded the OTA from the download link.
The way it is currently, it just deletes the zip and starts redownloading.

Thanks!

**Comment by xyyx** [comment]
Yes. I know. But I don't want to edit this code.
